name: Feature
description: New feature or enhancement
title: "feat: "
labels: ["type:feature"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What outcome do we want?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ]
        - [ ]
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes / Edge cases
