// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (id, project_id, title, description, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, title, description, status, created_at
`

type InsertTaskParams struct {
	ID          uuid.UUID `json:"id"`
	ProjectID   uuid.UUID `json:"project_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CreatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, project_id, title, description, status, created_at
FROM tasks
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListTasks(ctx context.Context, projectID uuid.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
  title = COALESCE($3, title),
  description = COALESCE($4, description),
  status = COALESCE($5, status)
WHERE project_id = $1 AND id = $2
RETURNING id, project_id, title, description, status, created_at
`

type UpdateTaskParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	ID          uuid.UUID   `json:"id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	Status      pgtype.Text `json:"status"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ProjectID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
